### ISSUE TITLE
Building profile fails after building VTK on Cygwin

### ISSUE THREAD

**Issue by johannesring** [hashdist/hashstack#262]
Using this simple profile for building VTK:

```
extends:
- file: cygwin.yaml
packages:
  launcher:
  python:
    host: true
  cmake:
    use: host-cmake
  vtk:
```

results in the following error on Cygwin:

```
johannr@Win764bitmpl ~/src/hashstack
$ hit build test-vtk.yaml
[profile] Building profile/uj54bln3xot3, follow log with:
[profile]   tail -f /home/johannr/.hashdist/tmp/profile-uj54bln3xot3/build.log
[profile ERROR] [Errno 2] No such file or directory: '/home/johannr/.hashdist/bld/profile/uj54bln3xot3/bin/Python/vtk' in silent_makedirs(u'/home/johannr/.hashdist/bld/profile/uj54bln3xot3/bin/Python/vtk',)
[profile ERROR] hit command failed: [Errno 2] [Errno 2] No such file or directory: '/home/johannr/.hashdist/bld/profile/uj54bln3xot3/bin/Python/vtk' in silent_makedirs(u'/home/johannr/.hashdist/bld/profile/uj54bln3xot3/bin/Python/vtk',)
```

Any idea?
