### ISSUE TITLE
boost in master seems to fail

### ISSUE THREAD

**Issue by certik** [hashdist/hashstack#342]
```
extends:
- file: linux.yaml

packages:

  launcher:
  blas:
    use: host-blas
  piranha:
  boost:
    toolset: gcc
    address_model: 64
  mpi:
    use: mpich
```

and

```
[cmake] Building cmake/tf6e2vnzs6pk, follow log with:
[cmake]   tail -f /home/ondrej/.hashdist/tmp/cmake-tf6e2vnzs6pk/build.log
^[[B[launcher] Building launcher/wvmh5uvayzv3, follow log with:
[launcher]   tail -f /home/ondrej/.hashdist/tmp/launcher-wvmh5uvayzv3/build.log
[host-blas] Building host-blas/ty7kho4fxa6q, follow log with:
[host-blas]   tail -f /home/ondrej/.hashdist/tmp/host-blas-ty7kho4fxa6q/build.log
[zlib] Building zlib/p7sxfw66vtas, follow log with:
[zlib]   tail -f /home/ondrej/.hashdist/tmp/zlib-p7sxfw66vtas/build.log
[mpich] Building mpich/h37o5xnm5aun, follow log with:
[mpich]   tail -f /home/ondrej/.hashdist/tmp/mpich-h37o5xnm5aun/build.log
[m4] Building m4/7j4mcywhajde, follow log with:
[m4]   tail -f /home/ondrej/.hashdist/tmp/m4-7j4mcywhajde/build.log
[patchelf] Building patchelf/fybv2nvzv5w5, follow log with:
[patchelf]   tail -f /home/ondrej/.hashdist/tmp/patchelf-fybv2nvzv5w5/build.log
[bzip2] Building bzip2/xtxmgx6fvc4c, follow log with:
[bzip2]   tail -f /home/ondrej/.hashdist/tmp/bzip2-xtxmgx6fvc4c/build.log
[gmp] Building gmp/q6o5ohstskvv, follow log with:
[gmp]   tail -f /home/ondrej/.hashdist/tmp/gmp-q6o5ohstskvv/build.log
[boost] Building boost/6uxnpftbjhbr, follow log with:
[boost]   tail -f /home/ondrej/.hashdist/tmp/boost-6uxnpftbjhbr/build.log
[boost ERROR] No such environment variable: u'MPICH_DIR'
```
