### ISSUE TITLE
Example profile on RHEL6

### ISSUE THREAD

**Issue by certik** [hashdist/hashstack#418]
This is using the default RHEL6 compilers (gcc 4.4.7)

```
extends:
- file: linux.yaml

packages:

  launcher:
  blas:
    use: lapack
  lapack:
    use: lapack
  mpi:
    use: mpich
  python:
    host: false
    build_with: |
      bzip2, openssl, sqlite
    link: shared
  swig:
    build_with: |
      perl
  ipython:
  nose:
  matplotlib:
  matplotlib-basemap:
  numpy:
  sphinx:
  sympy:
  gmp:
  opium:
  mercurial:
  doxygen:
  breathe:
  suitesparse:
  python-netcdf4:
  arb:
  gprof2dot:
  libunwind:
  scikit-learn:
  boost:
    toolset: gcc
    address_model: 64
    build_with: |
      python
  libstdcxx:
    use: host-libstdcxx
  gromacs:
  gcc:
  paraview:
    build_with: |
      mesa
  dftatom:
  git:
  subversion:
  pandas:
```

But it requires these PRs to get merged:
- [x] #412
- [x] #419
- [x] #485
- [x] #490
