### ISSUE TITLE
numpy isn't linked to any libraries as default. 

### ISSUE THREAD

**Issue by terjekv** [hashdist/hashstack#696]
After installing numpy via hashstack, the end result is somewhat disappointing:

$ module load FEniCS/1.5.0_2015.02.20_dev
$ python
imPython 2.7.8 (default, Feb 20 2015, 22:02:57) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
po>>> import numpy
>>> numpy.__config__.show()
lapack_info:
  NOT AVAILABLE
lapack_opt_info:
  NOT AVAILABLE
blas_info:
  NOT AVAILABLE
atlas_threads_info:
  NOT AVAILABLE
blas_src_info:
  NOT AVAILABLE
atlas_blas_info:
  NOT AVAILABLE
lapack_src_info:
  NOT AVAILABLE
openblas_info:
  NOT AVAILABLE
atlas_blas_threads_info:
  NOT AVAILABLE
blas_mkl_info:
  NOT AVAILABLE
blas_opt_info:
  NOT AVAILABLE
atlas_info:
  NOT AVAILABLE
lapack_mkl_info:
  NOT AVAILABLE
mkl_info:
  NOT AVAILABLE

This is solvable by editing the yaml file to include the following:

build_stages:

- when: platform == 'linux'
  name: create-site.cfg
  before: install
  handler: bash
  bash: |
    cat > site.cfg << EOF
    [blas]
    blas_libs = blas
    library_dirs = ${ARTIFACT}/lib
    [lapack]
    lapack_libs = lapack
    library_dirs = ${ARTIFACT}/lib
    EOF

But I'm not sure if that's a pretty solution.

**Comment by ahmadia** [comment]
Hmnn.  So you'd like NumPy to use the LAPACK libraries in the same way that SciPy does on Linux?  This seems reasonable to me.  @certik?

**Comment by certik** [comment]
I think something along these lines. The current numpy yaml is clearly broken:
```
extends: [distutils_package]
dependencies:
  build: [blas]
  run: [blas]

sources:
  - key: tar.gz:zzluhi5cjpyt4a3t7lvsicyi4sgrhhtd
    url: http://downloads.sourceforge.net/numpy/numpy-1.8.2.tar.gz

build_stages:

  - when: platform == 'linux'
    name: create-site.cfg
    before: install
    handler: bash
    bash: |
      cat > site.cfg << EOF
      [atlas]
      atlas_libs = openblas
      library_dirs = ${OPENBLAS_DIR}/lib
      EOF
```
As there is no dependency on openblas in numpy (and even if there was, that's not the way to go). We need to allow numpy to use the lapack implementation that is specified in the profile.
