### ISSUE TITLE
gmp.yaml package sets GMPXX_DIR rather than GMP_DIR

### ISSUE THREAD

**Issue by chvillanuevap** [hashdist/hashstack#714]
I noticed the gmp.yaml package sets the variable GMPXX_DIR to be equal to ARTIFACT:

```
when_build_dependency:
- set: GMPXX_DIR
  value: '${ARTIFACT}'
```

However, mpc and mpfr depend on GMP_DIR:

```
build_stages:
  - name: configure
    mode: override
    extra: ['--with-gmp=${GMP_DIR}']
```

Is using GMPXX_DIR correct? Otherwise, I'll correct this and initialize a pull request with the variable set to GMP_DIR in gmp.yaml.
