### ISSUE TITLE
Python fails to build on OS X Yosemite

### ISSUE THREAD

**Issue by certik** [hashdist/hashstack#726]
```
[python] checking size of float... 0
[python] checking size of double... 0
[python] checking size of fpos_t... 0
[python] configure: error: in `/Users/certik/.hashdist/tmp/python-gvp4myfkogce':
[python] configure: error: cannot compute sizeof (size_t)
[python] See `config.log' for more details
[python] checking size of size_t... 
[python|ERROR] Command '[u'/bin/bash', '_hashdist/build.sh']' returned non-zero exit status 77
[python|ERROR] command failed (code=77); raising
```
My profile is:
```
$ cat hd_base.yaml 
extends:
 - file: config.yaml

parameters:
  platform: Darwin
  PATH: /usr/bin:/bin:/usr/sbin:/sbin

packages:

  launcher:
  blas:
    use: host-osx-framework-accelerate
  lapack:
    use: host-osx-framework-accelerate
  mpi:
    use: mpich
  python:
    link: shared
  swig:
    build_with: |
      perl
  ipython:
  nose:
  numpy:
  sphinx:
  scipy:
  sympy:
  gmp:
  matplotlib:
  doxygen:
  breathe:
  #gcc:
  git:
  subversion:
  perl:
  pyliblzma:
```
Am I doing something wrong?

**Comment by certik** [comment]
The `config.log` says:
```
configure:7494: gcc -o conftest -g -O2 -I/Users/certik/.hashdist/bld/bzip2/bxiszvx5g3ps/include -I/Users/certik/.hashdist/bld/gdbm/3oc7ewslilpn/include -I/Users/certik/.hashdist/bld/launcher/wvmh5uvayzv3/include -I/Users/certik/.hashdist/bld/ncurses/bis3r7gbpr2u/include -I/Users/certik/.hashdist/bld/openssl/eeaesogvmrxm/include -I/Users/certik/.hashdist/bld/readline/dvdqxy3tqbre/include -I/Users/certik/.hashdist/bld/sqlite/aoao25jz2fvx/include -I/Users/certik/.hashdist/bld/zlib/2ervydrump5x/include -L/Users/certik/.hashdist/bld/bzip2/bxiszvx5g3ps/lib  -L/Users/certik/.hashdist/bld/gdbm/3oc7ewslilpn/lib  -L/Users/certik/.hashdist/bld/launcher/wvmh5uvayzv3/lib  -L/Users/certik/.hashdist/bld/ncurses/bis3r7gbpr2u/lib  -L/Users/certik/.hashdist/bld/openssl/eeaesogvmrxm/lib  -L/Users/certik/.hashdist/bld/readline/dvdqxy3tqbre/lib  -L/Users/certik/.hashdist/bld/sqlite/aoao25jz2fvx/lib  -L/Users/certik/.hashdist/bld/zlib/2ervydrump5x/lib  -Wl,-rpath,/Users/certik/.hashdist/bld/python/gvp4myfkogce/lib conftest.c  >&5
ld: warning: directory not found for option '-L/Users/certik/.hashdist/bld/launcher/wvmh5uvayzv3/lib'
ld: -rpath can only be used when targeting Mac OS X 10.5 or later
clang: error: linker command failed with exit code 1 (use -v to see invocation)
configure:7494: $? = 1
configure: program exited with status 1
configure: failed program was:
```

**Comment by certik** [comment]
I bet the problem is in not setting `MACOSX_DEPLOYMENT_TARGET`. I am now testing the following profile:
```
extends:
 - file: osx.yaml

packages:

  launcher:
  blas:
    use: host-osx-framework-accelerate
  lapack:
    use: host-osx-framework-accelerate
  mpi:
    use: mpich
  python:
    link: shared
  swig:
    build_with: |
      perl
  ipython:
  nose:
  numpy:
  sphinx:
  scipy:
  sympy:
  gmp:
  matplotlib:
  doxygen:
  breathe:
  #gcc:
  git:
  subversion:
  perl:
  pyliblzma:
```
Which correctly inherits from `osx.yaml`, which sets the `MACOSX_DEPLOYMENT_TARGET`.

**Comment by certik** [comment]
I used `examples/fenics.Darwin.yaml` as a template, and that profile does not set the `MACOSX_DEPLOYMENT_TARGET`, so I think it can't work, can it?

**Comment by certik** [comment]
For the record, the following profile finishes building:
```
extends:
 - file: osx.yaml

packages:

  launcher:
  blas:
    use: host-osx-framework-accelerate
  lapack:
    use: host-osx-framework-accelerate
  mpi:
    use: mpich
  python:
    link: shared
  swig:
    build_with: |
      perl
  ipython:
  nose:
  numpy:
  sphinx:
  sympy:
  gmp:
  matplotlib:
  doxygen:
  breathe:
  git:
  perl:
  pyliblzma:
```

Before we close this issue, we should see whether we need to update `examples/fenics.Darwin.yaml` to set the `MACOSX_DEPLOYMENT_TARGET`.
