### ISSUE TITLE
Working GCC profile on OS X 10.10

### ISSUE THREAD

**Issue by certik** [hashdist/hashstack#741]
Using the latest master (0e6de248224a2e340ec6f8ba9f10ef90d7a87788), and the default Xcode (installed automatically by OS X if you first type `gcc` into a terminal), this profile builds (among other things, gcc):
```
$ cat hd_base.yaml 
extends:
 - file: osx.yaml

packages:

  launcher:
  blas:
    use: host-osx-framework-accelerate
  lapack:
    use: host-osx-framework-accelerate
  mpi:
    use: mpich
  python:
    link: shared
  swig:
    build_with: |
      perl
  ipython:
  nose:
  numpy:
  sphinx:
  sympy:
  gmp:
  matplotlib:
  doxygen:
  breathe:
  gcc:
  git:
  perl:
  pyliblzma:
```
Once the `hd_base` profile is built, obtain it's path by:
```
$ ll hd_base
lrwxr-xr-x  1 certik  staff  48 May  1 09:46 hd_base@ -> /Users/certik/.hashdist/bld/profile/px524wdzacsz
```
and then use the following profile to build Hashstack (use the path from above in `PROLOGUE`):
```
extends:
 - file: osx.yaml

parameters:
  # First line is copied from osx.yaml (we cannot append to PROLOGUE yet)
  PROLOGUE: |
    export MACOSX_DEPLOYMENT_TARGET=$(sw_vers -productVersion | sed -E "s/([0-9]+\.[0-9]+).*/\1/"); export PATH="/Users/certik/.hashdist/bld/profile/px524wdzacsz/bin:$PATH"; export CC=gcc CXX=g++ FC=gfortran

packages:

  launcher:
  blas:
    use: host-osx-framework-accelerate
  lapack:
    use: host-osx-framework-accelerate
  mpi:
    use: mpich
  python:
    link: shared
  swig:
    build_with: |
      perl
  ipython:
  nose:
  numpy:
  sphinx:
  sympy:
  gmp:
  doxygen:
  breathe:
  perl:
  pyliblzma:
  git:
    disable_crypto: true
  csympy:
```
You need #743 in order for this to build. Then it builds nicely.

I will keep updating this issue with the latest progress. Eventually we'll make it an example in our examples directory and close this.

**Comment by certik** [comment]
Also, one really needs to also enable `fortran: true` in the second profile, otherwise `mpif90` isn't built and other packages like `scalapack` fail.

OS X shows that the path that we took on linux, that is build our own compilers and use those in Hashdist by default, is the right one. That should be the main way to get things going, and everything else like reusing compilers from the system should also work (that's the point of Hashdist, to be able to reuse systemwide packages and compilers), but obviously then one has to work on a case by case basis.

**Comment by cekees** [comment]
Thanks for posting this! I'm thinking of adding a `osxcompilers` target to the proteus Makefile that will allow  those without a a reliable gcc/g++/gfortran to first build something like this profile and then insert the path into the prologue.  Can I simplify it all the way down to the following?

```yaml
extends:
  - file: osx.yaml
packages:
  gcc:
```
