### ISSUE TITLE
Install repositories with no Makefiles

### ISSUE THREAD

**Issue by chvillanuevap** [hashdist/hashstack#792]
I would like to know how to install a package that does not contain a Makefile. For example, Catch (https://github.com/philsquared/Catch) is a header-only unit test framework. You can download a single header file under `single_include/catch.hpp`, or you can download multiple files and include them all using `include/catch.hpp`. As a header-only framework, Catch provides no Makefile.

How could I include Catch in my profile configuration, for example:

```
packages:
  catch:
  - key: git:xxxxxxxxxxxxxxxx
    url: https://github.com/philsquared/Catch
```

such that HashDist does not build anything, but does create an `include` directory in our profile, like `.hashdist/bld/profile/xxxxxxxx/include/catch.hpp`? Is there an example I can use as a model in HashStack?
