### ISSUE TITLE
choice of compilers (clang+gfortran) and package dependencies on OS-X

### ISSUE THREAD

**Issue by davydden** [hashdist/hashstack#875]
As a user i don't quite see how `hashdist/hashstack` choose compilers. Say If I want to build based on bare-bones osx using [osx_clt](https://github.com/hashdist/hashstack/blob/master/osx_clt.yaml) with clang for C/C++ and gfortran for Fortran 77 and 90, it's not obvious how to do it without using third-party package managers like `homebrew`. And even then it won't necessarily work.

If I look at [mpich](https://github.com/hashdist/hashstack/blob/master/pkgs/mpich.yaml) there is no settings related to compiler. Thus when I try to build at once something like
```
parameters:
  fortran: true

packages:
  launcher:
# gcc dependencies:
  zlib:
  mpfr:
  mpc:
  gmp:
  isl:
  cloog:
  gnu-sed:
## gcc:  
  gcc:
## the rest:
  cmake:
  python:
    host: true
  blas:
    use: host-osx-framework-accelerate
  lapack:
    use: host-osx-framework-accelerate
  mpi:
    use: mpich
```
the build order is such that `mpich` will be built before `gcc` and thus will fail as there will be no fortran compiler available. 

On another hand, even if I do some tricks and comment-out `mpi` and let the whole thing build, and then un-comment `mpi`, then I am absolutely not certain it will pick-up `clang` as C/C++ compiler and gfortran for Fortran. Judging by the fact that [gcc path will be prepended](https://github.com/hashdist/hashstack/blob/master/pkgs/gcc/gcc.yaml#L70-L72) I assume `mpich` will pick up gcc for everything.

Very likely developers are aware of this issue, but I thought i would rather mention it anyway just to be sure. Hopefully the solution is coming.
